export const STAFF_EMAIL_MAX_LENGTH = 50;
export const STAFF_USERNAME_MAX_LENGTH = 20;
export const STAFF_PHONE_NUMBER_MAX_LENGTH = 20;
export const STAFF_PASSWORD_MAX_LENGTH = 20;
export const STAFF_PASSWORD_MIN_LENGTH = 8;
export const STAFF_NAME_MAX_LENGTH = 100;
export const STAFF_ADDRESS_MAX_LENGTH = 20;
export const STAFF_GENDER_MAX_LENGTH = 20;
export const STAFF_ROLE_MAX_LENGTH = 20;

export const STAFF_HEALTH_INSURANCE_MAX_LENGTH = 100;
export const STAFF_STATUS_MAX_LENGTH = 10;
export const STAFF_DESCRIPTION_MAX_LENGTH = 500;
export const STAFF_EDUCATION_MAX_LENGTH = 500;
export const STAFF_CERTIFICATE_MAX_LENGTH = 500;
