export const FETCHING_API = "FETCHING_API";
export const FETCHING_API_SUCCESS = "FETCHING_API_SUCCESS";
export const FETCHING_API_FAILED = "FETCHING_API_FAILED";
export const SET_WAITING_INPUT = "SET_WAITING_INPUT";
